"""
Plan -> standalone Python. Deterministically.

WHY THE MODEL DOES NOT WRITE THIS CODE
--------------------------------------
Given a plan, there is exactly one right script, and producing it is
string formatting. Handing that to a language model adds a failure mode
(it forgets the VARIANT null, it adds parentheses to ForceEndEdit, it
helpfully refines the mesh) and buys nothing, because there was no
judgement left to exercise by the time the plan existed.

So the split is: the model decides WHAT to simulate, this file decides
HOW to write it, and the runtime prelude -- which neither of them
touches -- decides how to talk to COM. The only path back to generated
code is the `custom` operation, which is marked as such everywhere it
appears.

THE EMITTED SCRIPT IS STANDALONE
--------------------------------
It inlines the prelude rather than importing it, so a student can
download one file and run it on a machine that has never heard of this
project. That is also why the mesh floor is re-checked inside the
emitted file: once it is downloaded it is out of this project's hands,
and the check has to travel with it.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import datetime

from .. import config
from ..core import domains as D
from ..core.ops import ResolvedOp

_PRELUDE_RE = re.compile(
    r"# --- BEGIN RUNTIME PRELUDE.*?\n(.*?)\n# --- END RUNTIME PRELUDE ---",
    re.DOTALL)


def _prelude() -> str:
    """The runtime, read out of templates/runtime.py at emit time.

    Read rather than duplicated so there is one copy to fix when a COM
    quirk turns out to be wrong. The markers exist so the file stays a
    normal, importable, testable module instead of a blob of text."""
    source = (config.TEMPLATES_DIR / "runtime.py").read_text(encoding="utf-8")
    m = _PRELUDE_RE.search(source)
    if not m:
        raise RuntimeError(
            "templates/runtime.py is missing its PRELUDE markers. The "
            "emitter reads the runtime out of that file rather than "
            "keeping a second copy.")
    return m.group(1)


@dataclass
class Emitted:
    code: str
    domain: str
    unverified_ops: list[str]
    notes: list[str]


def _py(value) -> str:
    """A Python literal for a plan value. json.dumps handles the quoting
    and the unicode, and every value here is JSON-shaped by construction."""
    return json.dumps(value, ensure_ascii=False)


def _sel(op: ResolvedOp) -> str:
    if op.target is None:
        return "None"
    data = op.target.model_dump()
    data.pop("said", None)
    return _py({k: v for k, v in data.items() if v not in (None, "", [])})


def emit(domain: str, ops: list[ResolvedOp], study_name: str = "AI_Study",
         summary: str = "", assumptions: list[str] | None = None,
         warnings: list[str] | None = None,
         converge: bool = False) -> Emitted:
    spec = D.DOMAINS[domain]
    lines: list[str] = []
    notes: list[str] = []
    unverified = [o.op for o in ops if o.spec.confidence == "unverified"]

    # ---------------- header ----------------
    head = [
        '"""',
        f"Generated by the engineering assistant on "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}.",
        "",
        f"Study: {study_name}   Domain: {spec.label}",
    ]
    if summary:
        head += ["", f"Question: {summary}"]
    head += ["", "Plan:"]
    head += [f"  {i + 1}. {o.note or o.spec.label}" for i, o in enumerate(ops)]

    all_assumptions = list(assumptions or [])
    for o in ops:
        all_assumptions.extend(o.assumptions)
    if all_assumptions:
        head += ["", "Assumptions -- each of these is somewhere the answer",
                 "could be wrong for a reason you can see and correct:"]
        head += [f"  - {a}" for a in dict.fromkeys(all_assumptions)]
    if warnings:
        head += ["", "Warnings:"] + [f"  - {w}" for w in warnings]
    if unverified:
        head += [
            "",
            "API CONFIDENCE: this script uses calls that have NOT been run",
            "against a licensed install by this project:",
            f"  {', '.join(sorted(set(unverified)))}",
            "Review it before running it on a machine that matters. The",
            "physics and the numbers are checked; the COM signatures for",
            "these particular calls are reconstructed from documentation.",
        ]
    if spec.type_confidence == "unverified" and spec.study_type is not None:
        head += [
            "",
            f"The study type constant for {spec.label} ({spec.study_type}) is",
            "documented but unconfirmed here. The script reads the type back",
            "off the created study and stops if it does not match, so a wrong",
            "constant fails immediately instead of answering a different",
            "question.",
        ]
    head += ['"""', ""]

    lines.extend(head)
    lines.append(_prelude())
    lines.append("")
    lines.append("")
    lines.append("# " + "-" * 72)
    lines.append("# The plan")
    lines.append("# " + "-" * 72)
    lines.append("def main():")
    lines.append('    RECEIPT["domain"] = ' + _py(domain))
    lines.append('    RECEIPT["summary"] = ' + _py(summary))
    lines.append("    app = connect_to_solidworks()")

    ops = order_ops(ops)
    body: list[str] = []

    # Geometry comes first, then the add-in connection, then everything
    # else. The connection has to sit between them: Simulation binds to
    # whichever document is active, so connecting before the part exists
    # gives a study attached to nothing.
    if not any(o.op == "set_geometry" for o in ops):
        body += ["",
                 "    # No geometry step in the plan: use whatever is open.",
                 "    model = active_part(app)"]
    else:
        for op in [o for o in ops if o.op == "set_geometry"]:
            body.extend(_emit_op(op, domain))

    if any(o.target is not None and o.target.kind == "active_selection"
           for o in ops):
        # Read before anything else runs: a directional force selects a
        # reference plane, and that clears what the user picked.
        body += ["",
                 "    # What you have selected in SolidWorks, read first.",
                 "    capture_selection(model)"]

    body.append("")
    body.extend(_engine_setup(domain, study_name))

    for op in [o for o in ops if o.op != "set_geometry"]:
        body.extend(_emit_op(op, domain))

    if not any("write_receipt" in b for b in body):
        body += ["", "    write_receipt()"]

    wants_check = converge or any(
        o.op == "set_mesh" and o.options.get("convergence") == "check"
        for o in ops)
    if wants_check and spec.engine != D.FLOW and "    write_receipt()" in body:
        # After the first answer is read and before the plots and the
        # receipt: the check re-solves and keeps the finer result, and the
        # pictures should show that one.
        plots = f"    save_plots(study, {_py(domain)})"
        at = body.index(plots if plots in body else "    write_receipt()")
        body[at:at] = [f"    check_convergence(study, {_py(domain)})"]

    lines.extend(body)
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    try:")
    lines.append("        main()")
    lines.append("    except Exception as exc:")
    lines.append("        fail(exc)")
    lines.append("")

    return Emitted(code="\n".join(lines), domain=domain,
                   unverified_ops=sorted(set(unverified)), notes=notes)


# --------------------------------------------------------------------------
# Per-operation emission
# --------------------------------------------------------------------------
def _emit_op(op: ResolvedOp, domain: str) -> list[str]:
    fn = _EMITTERS.get(op.op)
    if fn is None:
        # A step with no emitter must NOT become a comment. The
        # catalogue is wider than the emitter on purpose -- recognising
        # "spin it at 3000 rpm" and saying the centrifugal load is not
        # wired up yet is more useful than not understanding it at all
        # -- but a script that silently skips a step the user asked for
        # runs, finishes, and answers a different question.
        #
        # The server refuses to emit at all when unsupported() is
        # non-empty; this is the second line of defence, for a script
        # emitted by some other path.
        return [
            f"    raise RuntimeError("
            f"{_py(f'This plan needs {op.spec.label} ({op.op}), which is in '
                   f'the operation catalogue but has no emitter yet. The '
                   f'step was NOT applied and the study was not run.')})"
        ]
    out = [""]
    if op.note:
        out.append(f"    # {op.note}")
    out.extend(fn(op, domain))
    return out


def _e_geometry(op: ResolvedOp, domain: str) -> list[str]:
    source = op.options.get("source", "active_document")
    if source == "active_document":
        return [
            "    model = active_part(app)",
            '    RECEIPT["geometry"] = {"source": "active_document"}',
        ]
    shape = op.options.get("primitive", "rectangular_beam")
    builder = PRIMITIVES.get(shape)
    if builder is None:
        return ["    model = new_part(app)",
                f"    raise RuntimeError("
                f"'No builder for primitive {shape}. Model it in "
                f"SolidWorks and re-run with source=active_document.')"]
    fn, args = builder
    values = ", ".join(repr(op.num(name, default)) for name, default in args)
    return ["    model = new_part(app)",
            f'    RECEIPT["geometry"] = {fn}(model, {values})']


# Every primitive the catalogue offers, with the runtime builder that
# makes it and the slots it reads in order (with the default each falls
# back to, in metres). The catalogue used to offer i_beam, box and
# cylinder with nothing here to build them: the plan was accepted, the
# script was written, and it stopped in SolidWorks on "No builder". A
# test now holds the two lists together.
PRIMITIVES: dict[str, tuple[str, tuple[tuple[str, float], ...]]] = {
    "rectangular_beam": ("build_rectangular_beam", (
        ("width", 0.05), ("height", 0.1), ("length", 1.0))),
    "box": ("build_box", (
        ("width", 0.05), ("height", 0.1), ("length", 1.0), ("wall", 0.0))),
    "round_bar": ("build_round_bar", (("diameter", 0.05), ("length", 1.0))),
    "cylinder": ("build_round_bar", (("diameter", 0.05), ("length", 1.0))),
    "tube": ("build_tube", (
        ("outer_diameter", 0.06), ("wall", 0.005), ("length", 1.0))),
    "i_beam": ("build_i_beam", (
        ("flange_width", 0.1), ("height", 0.2), ("web_thickness", 0.008),
        ("flange_thickness", 0.012), ("length", 2.0))),
    "plate": ("build_plate", (
        ("width", 0.2), ("length", 0.3), ("thickness", 0.005))),
    "plate_with_hole": ("build_plate_with_hole", (
        ("width", 0.1), ("length", 0.3), ("thickness", 0.01),
        ("hole_diameter", 0.025))),
    "angle_bracket": ("build_angle_bracket", (
        ("length", 0.12), ("height", 0.1), ("width", 0.06),
        ("thickness", 0.01), ("fillet_radius", 0.0),
        ("hole_diameter", 0.0))),
}


def _engine_setup(domain: str, study_name: str) -> list[str]:
    """Connect the right add-in and create the study.

    Which add-in depends on the domain, not on the operations: fluid
    mechanics and aerodynamics go through Flow Simulation, which is a
    different product from the Simulation add-in that everything else
    uses, with no study-type code and no shared object model."""
    if D.DOMAINS[domain].engine == D.FLOW:
        # No add-in connection yet. The checklist is printed first and the
        # connection happens at the solve step, so a machine with the
        # add-in switched off still gets the checklist.
        return [
            "    # Fluid domains go through the Flow Simulation add-in. This",
            "    # script prints the wizard checklist, then solves the part's",
            "    # Flow project and reads its goals -- if the project exists.",
            "    project = None",
        ]
    return [
        "    cw = connect_simulation(app)",
        f"    study = create_study(cw, {_py(study_name)}, {_py(domain)})",
    ]


def _e_material(op: ResolvedOp, domain: str) -> list[str]:
    name = op.options.get("name", "Plain Carbon Steel")
    db = op.options.get("database", "")
    return [f"    apply_material(study, {_py(name)}, {_py(db)})"]


def _e_mesh(op: ResolvedOp, domain: str) -> list[str]:
    if D.DOMAINS[domain].engine == D.FLOW:
        # Flow meshes are counted in cells and set through the project
        # wizard, not by element size. The level is recorded rather than
        # applied, for the same reason the project itself is: writing
        # unverified wizard calls would fail halfway through setup.
        level = int(op.num("level", 3) or 3)
        cells = int(op.num("max_cells", config.FLOW_MAX_CELLS)
                    or config.FLOW_MAX_CELLS)
        return [
            f'    RECEIPT["mesh"] = {_py({"level": level, "max_cells": cells})}',
            f"    warn('Initial mesh level {level} (cap {cells:,} cells) is "
            f"recorded in the receipt, not applied: the Flow Simulation "
            f"wizard API is not verified on this install. Set it in the "
            f"wizard.')",
        ]
    # Element sizes are held in millimetres and floored on both sides.
    max_mm = op.num("max_element", 0.0) * 1000.0 or 50.0
    min_mm = op.num("min_element", 0.0) * 1000.0 or 2.5
    max_mm = max(max_mm, config.MESH_MAX_ELEMENT_FLOOR_MM)
    min_mm = max(min_mm, config.MESH_MIN_ELEMENT_FLOOR_MM)
    # swsMeshQuality_e: draft 0, high 1. This line had them swapped, so
    # "draft" meshed second-order and "high" first-order.
    quality = "MESH_DRAFT" if op.options.get("quality") == "draft" else "MESH_HIGH"
    return [f"    create_mesh(study, {max_mm!r}, {min_mm!r}, {quality})"]


def _e_fixture(op: ResolvedOp, domain: str) -> list[str]:
    kind = op.options.get("type", "fixed")
    what = _py(op.note or f"the {kind} restraint")
    return [
        f"    entities = resolve(model, {_sel(op)}, {what})",
        f"    add_restraint(study, entities, {_py(kind)}, {what})",
    ]


def _e_force(op: ResolvedOp, domain: str) -> list[str]:
    """A force, with the direction the plan asked for.

    The direction used to be dropped here, so every load went on normal
    to the selected face. On the end face of a beam that is along the
    span -- the load compresses the beam instead of bending it, and the
    study solves and reports a stress that answers nothing."""
    per_entity = op.options.get("distribution") == "per_entity"
    direction = op.options.get("direction", "normal")
    what = _py(op.note or "the force")
    return [
        f"    entities = resolve(model, {_sel(op)}, {what})",
        f"    add_force(study, model, entities, {op.num('magnitude')!r}, "
        f"{_py(direction)}, {per_entity!r}, {what})",
    ]


def _e_pressure(op: ResolvedOp, domain: str) -> list[str]:
    what = _py(op.note or "the pressure")
    return [
        f"    entities = resolve(model, {_sel(op)}, {what})",
        f"    add_pressure(study, entities, {op.num('magnitude')!r}, {what})",
    ]


def _e_gravity(op: ResolvedOp, domain: str) -> list[str]:
    return [f"    add_gravity(study, {op.num('magnitude', 9.80665)!r}, "
            f"{_py(op.options.get('direction', 'against_y'))})"]


def _e_temperature(op: ResolvedOp, domain: str) -> list[str]:
    what = _py(op.note or "the prescribed temperature")
    return [
        f"    entities = resolve(model, {_sel(op)}, {what})",
        f"    add_temperature(study, entities, "
        f"{op.num('temperature')!r}, {what})",
    ]


def _e_convection(op: ResolvedOp, domain: str) -> list[str]:
    what = _py(op.note or "convection")
    return [
        f"    entities = resolve(model, {_sel(op)}, {what})",
        f"    add_convection(study, entities, {op.num('film_coefficient')!r}, "
        f"{op.num('bulk_temperature')!r}, {what})",
    ]


def _e_heat_power(op: ResolvedOp, domain: str) -> list[str]:
    what = _py(op.note or "the heat source")
    return [
        f"    entities = resolve(model, {_sel(op)}, {what})",
        f"    add_heat_power(study, entities, {op.num('power')!r}, {what})",
    ]


def _e_heat_flux(op: ResolvedOp, domain: str) -> list[str]:
    what = _py(op.note or "the heat flux")
    return [
        f"    entities = resolve(model, {_sel(op)}, {what})",
        f"    add_heat_flux(study, entities, {op.num('heat_flux')!r}, {what})",
    ]


def _e_radiation(op: ResolvedOp, domain: str) -> list[str]:
    what = _py(op.note or "radiation")
    return [
        f"    entities = resolve(model, {_sel(op)}, {what})",
        f"    add_radiation(study, entities, {op.num('emissivity', 0.9)!r}, "
        f"{op.num('ambient_temperature', 293.15)!r}, "
        f"{op.num('view_factor', 1.0) or 1.0!r})",
    ]


def _e_flow_domain(op: ResolvedOp, domain: str) -> list[str]:
    """Flow Simulation project creation.

    Emitted as a recorded, refusing stub rather than as invented COM
    calls. Writing plausible-looking Flow Simulation API calls that were
    never run would produce a script that fails somewhere in the middle,
    after creating a project, with a COM error naming a method the user
    has never heard of. Stating the limit up front and writing the
    complete setup into the receipt is more useful: the user can build
    the project through the wizard in about a minute with every number
    already decided and checked."""
    settings = {
        "analysis_type": op.options.get("analysis_type", "internal"),
        "fluid": op.options.get("fluid", "Air"),
        "flow_type": op.options.get("flow_type", "laminar_and_turbulent"),
        "heat_conduction": op.options.get("heat_conduction", "off"),
        "gravity": op.options.get("gravity", "off"),
        "time": op.options.get("time", "steady"),
        "ambient_pressure_Pa": op.num("ambient_pressure", 101325.0),
        "ambient_temperature_K": op.num("ambient_temperature", 293.15),
        "velocity_m_s": op.num("velocity", 0.0),
        "turbulence_intensity_pct": op.num("turbulence_intensity", 0.0),
    }
    return [f'    RECEIPT["flow_project"] = {_py(settings)}']


def _e_flow_bc(op: ResolvedOp, domain: str) -> list[str]:
    bc = {
        "type": op.options.get("type", ""),
        "target": op.target.describe() if op.target else "",
        **{k: v.value for k, v in op.q.items()},
    }
    return [f'    RECEIPT.setdefault("flow_bcs", []).append({_py(bc)})']


def _e_goal(op: ResolvedOp, domain: str) -> list[str]:
    goal = {"quantity": op.options.get("quantity", ""),
            "scope": op.options.get("scope", "global"),
            "target": op.target.describe() if op.target else "whole model"}
    return [f'    RECEIPT.setdefault("goals", []).append({_py(goal)})']


def _e_frequency_options(op: ResolvedOp, domain: str) -> list[str]:
    """How many modes to extract.

    Through the runtime helper rather than inline: ICWStudy has no
    SetFrequencyOptions method at all, which is what this used to call,
    so the mode count quietly stayed at the study's default."""
    modes = int(op.num("modes", 5) or 5)
    return [f"    set_frequency_modes(study, {modes}, {_py(domain)})"]


def _e_solve(op: ResolvedOp, domain: str) -> list[str]:
    if D.DOMAINS[domain].engine == D.FLOW:
        # The checklist goes out first -- boundary conditions and goals are
        # recorded by now -- then the part's own project, if it has one.
        return [
            "    print_flow_setup(RECEIPT)",
            '    project = flow_project(app, model, RECEIPT.get("flow_project"))',
            "    if project is not None:",
            "        solve_flow(project)",
        ]
    return ["    solve(study)"]


def _e_results(op: ResolvedOp, domain: str) -> list[str]:
    if D.DOMAINS[domain].engine == D.FLOW:
        return ["    if project is not None:",
                "        read_flow_goals(project)",
                "    write_receipt()"]
    return [
        f"    read_results(study, {_py(domain)})",
        f"    save_plots(study, {_py(domain)})",
        "    keep_part()",
        "    write_receipt()",
    ]


def _e_custom(op: ResolvedOp, domain: str) -> list[str]:
    """A custom step is the one place generated code can enter.

    It is emitted as a refusing placeholder here; the server fills it in
    from a separate, RAG-grounded generation pass and re-validates the
    whole script afterwards. Emitting a stub rather than silently
    dropping the step means a plan that depended on it cannot run and
    quietly skip the thing the user asked for."""
    instruction = op.options.get("instruction", "")
    return [
        f"    # CUSTOM STEP -- generated separately: {instruction}",
        f"    raise RuntimeError({_py('Custom step was not filled in: ' + instruction)})",
    ]


_EMITTERS = {
    "set_geometry": _e_geometry,
    "apply_material": _e_material,
    "set_mesh": _e_mesh,
    "add_fixture": _e_fixture,
    "add_force": _e_force,
    "add_pressure": _e_pressure,
    "add_gravity": _e_gravity,
    "add_temperature": _e_temperature,
    "add_convection": _e_convection,
    "add_heat_power": _e_heat_power,
    "add_heat_flux": _e_heat_flux,
    "add_radiation": _e_radiation,
    "set_flow_domain": _e_flow_domain,
    "add_flow_bc": _e_flow_bc,
    "add_goal": _e_goal,
    "set_frequency_options": _e_frequency_options,
    "solve": _e_solve,
    "extract_results": _e_results,
    "custom": _e_custom,
}


def supported_ops() -> set[str]:
    """Which operations to offer the planner, and to accept in a plan.

    `custom` is deliberately not in here. It emits a placeholder that
    raises, because the RAG-grounded generation pass meant to fill it in
    does not exist -- so a plan carrying one produces a script that
    builds the study, applies the loads and then dies before solving.
    Left out, the model is never offered it, and unsupported() refuses a
    plan that contains one by some other route."""
    return set(_EMITTERS) - {"custom"}


def unsupported(ops: list[ResolvedOp]) -> list[str]:
    """Operations in this plan that the emitter cannot write yet.

    The catalogue is deliberately wider than the emitter. Recognising
    "spin it at 3000 rpm" as a centrifugal load and saying so beats
    failing to understand it -- but the gap has to be surfaced at PLAN
    time, as a sentence in the panel, rather than at run time as a
    script that stops halfway through.

    Derived from supported_ops() rather than from a second flag on the
    spec, because two lists of the same thing drift apart and the one
    that drifts is always the one nothing tests."""
    return sorted({op.op for op in ops if op.op not in supported_ops()})


def order_ops(ops: list[ResolvedOp]) -> list[ResolvedOp]:
    """Put the plan in an order SolidWorks will accept.

    The model produces steps in the order the user said them, which is
    the order a person thinks in and not the order the API requires:
    a material cannot be assigned before a study exists, loads cannot be
    applied before a mesh, and nothing can be read before a solve. Sorting
    here means the planner never has to be told about sequencing, which
    is one fewer instruction for it to half-follow."""
    rank = {
        "set_geometry": 0, "set_flow_domain": 1, "apply_material": 2,
        "set_solver": 3, "set_frequency_options": 3, "set_mesh": 4,
        "add_fixture": 5,
        "add_force": 6, "add_pressure": 6, "add_torque": 6,
        "add_gravity": 6, "add_centrifugal": 6, "add_bearing_load": 6,
        "add_remote_load": 6, "add_initial_velocity": 6,
        "add_temperature": 6, "add_convection": 6, "add_heat_flux": 6,
        "add_heat_power": 6, "add_radiation": 6,
        "add_flow_bc": 6, "add_fan": 6, "add_porous_medium": 6,
        "add_rotating_region": 6, "add_goal": 7,
        "custom": 8, "solve": 9, "extract_results": 10,
    }
    return sorted(ops, key=lambda o: rank.get(o.op, 6))
